### ISSUE TITLE
Tabs in tabs are not working

### ISSUE THREAD

**Issue by csakiistvan** [janmarkuslanger/tabby#2]
If I create a tab, and make a new tabs with different data-tabs-item and data-tabs-content names the second tabs switch is not working.

![Tabs in tabs](https://www.evernote.com/l/AA0rDo-BG95AcITtQbn6sGGLb0PTslSD5-0B/image.png)

**Comment by janmarkuslanger** [comment]
Hey there @csakiistvan  sorry for the late response. :(

 Can you show me the code.
I will looking for a solution. :) 

Have a nice day.

**Comment by janmarkuslanger** [comment]
I will looking for a solution asap.

**Comment by csakiistvan** [comment]
There is an example markup https://gist.github.com/csakiistvan/dea7bc510ebbb50cf2960bbd1526c626

**Comment by janmarkuslanger** [comment]
Thank you. I´m going to fix that soon.

**Comment by janmarkuslanger** [comment]
Hey there! 

Hopefully i have a solutution now. You need to do following steps
- Upgrade to 2.0.0 / Include the css / js file from the dist folder
- Change the HTML Attributes to 2.0.0 

I made a gist for tabs in tabs https://gist.github.com/janmarkuslanger/0560582d2fee1474031378317d0107a7

Let me know if this works now.

**Comment by csakiistvan** [comment]
Please upgrade the library on this website https://www.npmjs.com/package/tabsjs-lib

**Comment by janmarkuslanger** [comment]
@csakiistvan i published the version 2.0.1 on npm a few minutes ago.
https://www.npmjs.com/package/tabsjs-lib

**Comment by csakiistvan** [comment]
Thanks the update. Unfortunately It is not works for me. I Updated the all attributes, and the main tabs is working, but the secondary is not. If I modify the class to only the secondary tab is is working, but two do not work at the same time

There is my init, and all tabs element has tabs class.
`<script>
    const myTab = new Tabby.Component(document.querySelector('.tabs'), {});
  </script>
`

**Comment by janmarkuslanger** [comment]
Hey there. I changed the following thing in this fix. 
Every time you create a new Tabby Component it will catch the first bar item and then it will get all its siblings and not just every bar items it can get. So you need to create a new Component for each element. 

``` javascript

const myTabs = [].slice.call(document.querySelectorAll('.tabs'));
myTabs.forEach((tab) => {
  new Tabby.Component(tab);
});

```

should work for you. :)

**Comment by csakiistvan** [comment]
It is working now, ❤️ and ✌🏼

**Comment by janmarkuslanger** [comment]
Perfect. Have a nice day :)
