### ISSUE TITLE
How to use / import tabby with webpack? v3

### ISSUE THREAD

**Issue by juandinella** [janmarkuslanger/tabby#7]
How should import and use the lib with Webpack and ES6 Modules? I imported this way 
`import Tabby from 'tabsjs-lib/dist/tabby.iife'`

But I get `Uncaught TypeError: tabsjs_lib_dist_tabby_iife__WEBPACK_IMPORTED_MODULE_0___default.a.init is not a function`

Thanks

**Comment by janmarkuslanger** [comment]
Did you install tabby via npm?

**Comment by juandinella** [comment]
> Did you install tabby via npm?

Yes I did

**Comment by janmarkuslanger** [comment]
If you install it via npm you can use tabby like this: 

``` javascript
import { init } from 'tabsjs-lib';
init(); 
```

or like this 

```javascript
const Tabby = require('tabsjs-lib');
Tabby.init();
```

Let me know if this works for you. 🤔

**Comment by janmarkuslanger** [comment]
@juandinella Is it working for you?

**Comment by juandinella** [comment]
It's working perfect. Thanks!

**Comment by janmarkuslanger** [comment]
Great if you like it feel free to share and like it! ⭐️
