### ISSUE TITLE
Toggle next bar element function

### ISSUE THREAD

**Issue by juandinella** [janmarkuslanger/tabby#8]
Besides the main list, I have a link to the next tab and I can't make it work. Any idea?

```
<li data-tabby-bar="1" data-tabby-active>1</li>
<li data-tabby-bar="2">2</li>

<div data-tabby-content="1" data-tabby-active>
  <button data-tabby-bar="2"> Next
</div>
<div data-tabby-content="2"></div>

```

And thanks again

**Comment by janmarkuslanger** [comment]
Hey there again!

To make sure I really understand you. Do you want to know how to add the small lines between the bar elements?

**Comment by juandinella** [comment]
Nono, I want to click in 'Next Step' and I want to to go to the tab number 2

edit: https://codepen.io/juandinella/pen/ZwKGVd

**Comment by janmarkuslanger** [comment]
Ahh, sorry! This might be a good feature. For now, I will help you with your case. Do you have multiple tab elements on your page or just the one? Should the "Next step" link in every content element?

**Comment by juandinella** [comment]
I have multiples tab elements But in those 4 steps I have a 'next step' in the first three

**Comment by janmarkuslanger** [comment]
I am going to fork your codepen project and try my best 😄

**Comment by janmarkuslanger** [comment]
Okay, I got something. 
The best way would be to add a class to your buttons. In my case it was `.js--toggle-next`.

Then I added the following code: 
``` javascript 
(function(){
  
  // get all the next buttons 
  const nextButtons = [].slice.call(document.querySelectorAll('.js--toggle-next'));
 
  const findTabbyContainer = (element) => {
      let testElement = element.parentElement;
      while(testElement.getAttribute('data-tabby') === null) {
        testElement = testElement.parentElement;
      }
    
    return testElement;
  };
  
  const getActiveBar = container => container.querySelector('[data-tabby-bar][data-tabby-active]');
  
  const getNextBar = (bar) => {
    let testElement = bar.nextElementSibling;
    
    while(testElement.getAttribute('data-tabby-bar') === null) {
      testElement = testElement.nextElementSibling;
    }
    
    return testElement;
  };
  
  const toggleNext = (button) => {
     const container = findTabbyContainer(button);
     const activeBar = getActiveBar(container);
     const nextBar = getNextBar(activeBar);
    
    nextBar.click();
  };
  
  nextButtons.forEach((button) => {
    button.addEventListener('click', () => {
      toggleNext(button); 
    });
  });
  
}());
```

Here is the Codepen link: https://codepen.io/janmarkuslanger/pen/Lqyppy?editors=1111

I will definitely add this when I am working on the API of this project.

**Comment by janmarkuslanger** [comment]
@juandinella let me know if this is working for you, please. 😄

**Comment by juandinella** [comment]
More than perfect @janmarkuslanger Thank you so much!

**Comment by janmarkuslanger** [comment]
@juandinella you are wellcome!

**Comment by janmarkuslanger** [comment]
@juandinella in the current version 3.1.0 you can use methods like `next()` :) 
https://github.com/janmarkuslanger/tabby#methods-next
